# Generated by Django 6.0.3 on 2026-04-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование корпуса')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование отдела')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование статуса')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование типа')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название фото')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='RepairStage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('technician', 'Техник'), ('employee', 'Сотрудник')], max_length=250, unique=True, verbose_name='Наименование')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за 1 шт.')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyService',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование модели')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.manufacturer', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер кабинета')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.building', verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('inventory_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Инвентарный номер')),
                ('configuration', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('purchase_date', models.DateField(verbose_name='Дата приобретения')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.equipmentmodel', verbose_name='Модель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.equipmentstatus', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.equipmenttype', verbose_name='Тип оборудования')),
                ('assigned_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.office', verbose_name='Закрепленный кабинет')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.photos', verbose_name='Фото')),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.warranty', verbose_name='Гарантия')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=250, unique=True, verbose_name='Почта (Логин)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=250, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=250, verbose_name='Отчество')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего захода')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.department', verbose_name='Отдел')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equip.office', verbose_name='Кабинет')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.position', verbose_name='Должность')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='RequestFix',
            fields=[
                ('act_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер акта')),
                ('problem_description', models.CharField(max_length=500, verbose_name='Описание неисправности')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('comment_technician', models.TextField(blank=True, null=True, verbose_name='Комментарий техника')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned', to='equip.employee', verbose_name='Назначенный исполнитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.requestcategory', verbose_name='Категория')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.equipment', verbose_name='Оборудование')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.priority', verbose_name='Приоритет')),
                ('repair_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.repairstage', verbose_name='Этап ремонта')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='equip.employee', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSparePart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('cost_at_repair', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент ремонта')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_spare_parts', to='equip.requestfix', verbose_name='Заявка')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.sparepart', verbose_name='Запчасть')),
            ],
        ),
        migrations.AddField(
            model_name='requestfix',
            name='spare_parts',
            field=models.ManyToManyField(blank=True, through='equip.RequestSparePart', through_fields=('request', 'spare_part'), to='equip.sparepart', verbose_name='Запчасти'),
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('cost_at_repair', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент ремонта')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('receipt_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equip.file', verbose_name='Чек (файл)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_services', to='equip.requestfix', verbose_name='Заявка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equip.thirdpartyservice', verbose_name='Услуга')),
            ],
        ),
        migrations.AddField(
            model_name='requestfix',
            name='services',
            field=models.ManyToManyField(blank=True, through='equip.RequestService', through_fields=('request', 'service'), to='equip.thirdpartyservice', verbose_name='Услуги'),
        ),
    ]
